language: node_js
node_js: "lts/*"
services:
  - docker
before_install:
  - cd src
install:
  - npm install
  - npm install -g codecov
before_script:
  - ./../deploy/create-settings-file.sh
after_success:
  - ./../deploy/docker-build-and-push.sh
notifications:
  email: false