language: node_js
node_js: "lts/*"
services:
  - docker
install:
  - npm install -g codecov
before_script:
  - ./deploy/create-settings-file.sh
  - cat settings.json
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker build -f ./deploy/docker/Dockerfile -t rzinnatov/remoteml-lss:latest .
  - docker push rzinnatov/remoteml-lss:latest
cache:
  directories:
    - "node_modules"
